### ISSUE TITLE
Recipe 11.4 'Adding Liveness & Readiness Probe to your Deployments'

### ISSUE THREAD

**Issue by bennybhlin** [k8s-cookbook/recipes#10]
Using example code 'webserver.yaml' here to run 'kubectl create -f webserver.yaml', it would produce error message below:

![default](https://user-images.githubusercontent.com/38855622/47001378-df65fe80-d15c-11e8-8da0-132790ff8574.png)

Is it caused by empty name: & image: below containers: section? But when I added 'nginx' to name: and 'nginx:stable' to 'image:', there was another error:

![default](https://user-images.githubusercontent.com/38855622/47001638-83e84080-d15d-11e8-9a59-e13dc72e5835.png)

Looks like another format problem to me.

**Comment by mhausenblas** [comment]
Thanks @bennybhlin you indeed found a bug :)

Fixed now.

**Comment by bennybhlin** [comment]
Hi Michael

Please add 2 more points before you close this issue :-D

1. Your 'name: webserver' should be indented under metadata section, or you'll get this error:

error: error validating "webserver.yaml": error validating data: [ValidationErro                                                                                        r(Deployment): unknown field "name" in io.k8s.api.extensions.v1beta1.Deployment

2. Please correct all initialDelaySecond as 'initialDelaySeconds', or you'll get this error:

ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unk                                                                                        nown field "initialDelaySecond" in io.k8s.api.core.v1.Probe, ValidationError(Dep                                                                                        loyment.spec.template.spec.containers[0].readinessProbe): unknown field "initial                                                                                        DelaySecond" in io.k8s.api.core.v1.Probe]

**Comment by bennybhlin** [comment]
Hi Michael

2 more points to fix:

1. name field of deployment should be indented
2. both initialDelaySecond should be initialDelaySeconds

FYI

Michael Hausenblas <notifications@github.com> 於 2018年10月16日 週二 下午6:41寫道：

**Comment by mhausenblas** [comment]
Ouch, sorry for that, should have tested again before closing! I hope it's OK now @bennybhlin?

**Comment by bennybhlin** [comment]
Yup, you can close it again a last, it's created as expected.

Michael Hausenblas <notifications@github.com> 於 2018年10月17日 週三 下午3:45寫道：

**Comment by mhausenblas** [comment]
Thanks a bunch @bennybhlin for confirming it!
