### ISSUE TITLE
The issue inside a cluster when trying k8s-cookbook recipe 5.2 'Verifying a DNS entry of a service'

### ISSUE THREAD

**Issue by bennybhlin** [k8s-cookbook/recipes#2]
This issue is related to k8s-cookbook recipe 5.2 'Verifying a DNS entry of a service'

I used a VMWare workstation player to install 2 VMs with Ubuntu 16.04 LTS, and installed Docker 18.06CE / Kubeadm 1.7.8 / Weave Network as my test environment (I knew there is Kuberentes 1.12 ready but I stll got this very same problem a few weeks ago, hence I decided to fall-back to version 1.7 you mentioned in this book).

Thing went well for all components installation until I completed 'kubeadm init' & 'kubeadm join' & created a few pods/svc. When I followed section 5.2 to launch busybox interactively, using 'nslookup nginx' simply returned an error: ";; connection timed out; no servers could be reached". I am pretty sure that my components are up 'n running:

my kube-dns pod was running (EndPoint IP 10.32.0.3) & DNS service is up (ClusterIP 10.96.0.10)
my nginx pod was running (EndPoint IP 10.32.0.2) & nginx service is exposed (ClusterIP 10.105.192.35)

However, when I checked logs of my kubedns pod and its container sidecar, lots of error entries there:

ERROR: logging before flag.Parse: W1009 07:13:42.157859      24 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:37999->127.0.0.1:53: i/o timeout

Looks like while my sidecar is probing health of dnsmasq, it's not healthy (but don't know why)

I was curious, since neither my busybox nor my master node knew how to reach 10.96.0.10 (none of their routing tables (route -n) has effective route to it); I wonder maybe I missed some critical points? Do I need to tune weave network to allow pods and nodes can talk?

**Comment by mhausenblas** [comment]
Since I can't reproduce the setup easily, can you do me a favour and try the following since I have a hunch that this might be the root cause: you're using Docker 1.18 where (at least for Kube 1.7, I think this hasn't changed dramatically) you should be using Docker 1.12. Can you verify if you get the same error with this Docker version?

**Comment by sebgoa** [comment]
Also, can you make sure to use `busybox:1.28` there is a problem with `busybox:latest` which causes the dns lookup to fail.

**Comment by bennybhlin** [comment]
Thanks Sebastien, I will definitely try that as well.

Will let you & Michael know my finding asap.

Benny

sebgoa <notifications@github.com> 於 2018年10月10日 週三 上午3:41寫道：

**Comment by bennybhlin** [comment]
Good news

Although I installed Docker 1.12.6-cs13 but still got same busybox/dns query error

However, using busybox v1.28.4 did get rid of my pain (yapee~)

![default](https://user-images.githubusercontent.com/38855622/46715813-2606b500-cc94-11e8-99e6-66d5761ff4a8.png)


Appreciate you two kind gentlemen to show me a working path
