### ISSUE TITLE
The issue inside a cluster when trying k8s-cookbook recipe 5.1 'Creating a Service to Expose Your Application' 

### ISSUE THREAD

**Issue by bennybhlin** [k8s-cookbook/recipes#3]
This issue is related to k8s-cookbook recipe 5.1 'Creating a Service to Expose Your Application'

Still I used a VMWare workstation player to install 2 VMs with Ubuntu 16.04 LTS, but retuned to install Docker 1.12.6-cs13 / Kubeadm 1.12.1 / Weave Network as my test environment.

Thing went weird until I followed section 5.1 to expose nginx service then launch 'kubectl proxy', using 'curl http://localhost:8001/api/v1/proxy/namespaces/default/services/nginx/' simply returned an error:

![default](https://user-images.githubusercontent.com/38855622/46717317-0b373f00-cc9a-11e8-9dca-2bfcb6bbc6af.png)

If I simply view by 'curl http://localhost:8001/api/v1/' I could still get responded:

![default](https://user-images.githubusercontent.com/38855622/46717979-6407d700-cc9c-11e8-90cf-c90cc14eadeb.png)
 

my nginx pod was running (EndPoint IP 10.32.0.5) & nginx service is exposed (ClusterIP 10.105.135.102)

*ps: This time my CoreDNS pod are running well without CrashedLoop error. Last round I combined Docker CE 18 & Kubernetes 1.12 but CoreDNS went weird so I gave it up & turned back to Kubernetes 1.7.8 to hit flank. However, this round it's Docker 1.12.6 & Kubernetes 1.12 & everything is fine (except proxy issue above)

I wonder is it another version-compatibility problem again?

**Comment by mhausenblas** [comment]
Can you check against the [troubleshooting checklist](http://troubleshooting.kubernetes.sh/#network) to see if you can get to it from within the cluster and directly to the pod?

**Comment by bennybhlin** [comment]
BTW, while I tried to access exposed nginx svc from master node (curl http://10.105.135.102), it's responding:

![default](https://user-images.githubusercontent.com/38855622/46718954-66b7fb80-cc9f-11e8-9ab4-10f85218458a.png)

**Comment by sebgoa** [comment]
This endpoint has changed in recent k8s versions:
'curl http://localhost:8001/api/v1/proxy/namespaces/default/services/nginx/'

TRY:

'curl http://localhost:8001/api/v1/namespaces/default/services/nginx/proxy'

**Comment by bennybhlin** [comment]
Thanks Sebastien, new URL does work (OMG this made me stuck over a few weeks)
