### ISSUE TITLE
Regarding on recipes 7.4

### ISSUE THREAD

**Issue by bennybhlin** [k8s-cookbook/recipes#4]
Hello it's me again

I tested both yaml and shell script files in recipe 7.4; when I launch Kubernetes dashboard to view the result, I could see both cockroachdb & cockroachdb-public services were there, however none StatefulSet (cockroachdb) was displayed.

Furthermore, I had to grant admin privileges to Dashboard's Service Account so I could access (skip login) dashboard. This is not mentioned in K8s cookbook. Is it another version issue?

**Comment by mhausenblas** [comment]
> however none StatefulSet (cockroachdb) was displayed.

Not sure what you mean. Does `kubectl get sts` give you something?

> Furthermore, I had to grant admin privileges to Dashboard's Service Account so I could access (skip login) dashboard. This is not mentioned in K8s cookbook. Is it another version issue?

This is covered in a different recipe, so you can ignore it.

**Comment by bennybhlin** [comment]
Nope, even using kubectl get sts --all-namespaces it still replied 'No resources found'

**Comment by mhausenblas** [comment]
Interesting. Also no pods and PVs?

**Comment by bennybhlin** [comment]
It's funny, pv0~3 were created as expected, but none POD with names like cockroachdb*

**Comment by bennybhlin** [comment]
Hi

I found the root cause; it's simply caused by the way I copied cockroachdb-statefulset.yaml from here to my Putty screen: the last line 'storage: 1Gi' was not correctly indented 2 characters behind the above line 'requests:', like this:

      resources:
        requests:
storage: 1Gi

After I correct it as below, thing went well as expected:

      resources:
        requests:
          storage: 1Gi

I had no idea that yaml is so format-sensitive, how embarrased I am.

**Comment by mhausenblas** [comment]
Yup, that's YAML for you, welcome to my world ;)
