### ISSUE TITLE
Recipe 9.4 'Using Horizontal Pod Autoscaling on GKE'

### ISSUE THREAD

**Issue by bennybhlin** [k8s-cookbook/recipes#7]
Before creating this svc/appserver, readers had to prepare a working cluster first; furthemore, the cluster must own enough vCPU so it can support 2 workloads appserver & loadgen; otherwise there would be 'not enough vCPU' error again.

![default](https://user-images.githubusercontent.com/38855622/46942311-a1ef6b80-d09f-11e8-8c84-a600e129c5b1.png)

And readers must run gcloud container clusters get-credentials again, otherwise there would be error below:

error: failed to discover supported resources: Get http://localhost:8080/apis/extensions/v1beta1: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

After cluster creation and access was available, then readers could run appserver & loadgen to test this recipe.

**Comment by mhausenblas** [comment]
Hmm, did you use the version we used in the book?

**Comment by bennybhlin** [comment]
Do you mean my GKE version?

**Comment by mhausenblas** [comment]
Yes, GKE version.

**Comment by bennybhlin** [comment]
Mine is SDK 218.0.0, does it matter?

![default](https://user-images.githubusercontent.com/38855622/47063802-5f4ca100-d20f-11e8-861c-9a17cb49279d.png)

**Comment by mhausenblas** [comment]
Erm, not the version of `gcloud` but the GKE version ;)

**Comment by bennybhlin** [comment]
Sorry I did not get your point, it is GKE 1.9.7.

![default](https://user-images.githubusercontent.com/38855622/47068347-9fffe680-d21e-11e8-8abb-fc25afea99bf.png)

**Comment by mhausenblas** [comment]
Yeah, again, we stated in the preface we're using Kubernetes 1.7 and things change. Not much we can do in the book until we release a 2nd Edition.

**Comment by bennybhlin** [comment]
Understood, I'll add comments in translation to highlight this difference.

Michael Hausenblas <notifications@github.com> 於 2018年10月17日 週三 下午3:42寫道：

**Comment by mhausenblas** [comment]
Thank you @bennybhlin and I'll leave this one open for us to take on board for the next edition.
