### ISSUE TITLE
Recipe 10.1 Providing a Unique Identity for an Application

### ISSUE THREAD

**Issue by bennybhlin** [k8s-cookbook/recipes#8]
In sample code of recipe 10.1, the namespace of pod myapp was wrongly assigned to 'sec', this may introduce error message:

Error from server (NotFound): error when creating "pod-with-sa.yaml": namespaces "sec" not found

Since serviceaccount 'myappsa' was created under namespace/default, so this should be easily corrected.

**Comment by mhausenblas** [comment]
I'm not following. How is 5.1 relevant here? I double checked 10.1 and I can't find the error. What exactly seems to be the problem @bennybhlin?

**Comment by bennybhlin** [comment]
It's my typo - I'd correct it as '10.1'. If I copy sample code of 10.1 in this site, the error came out.

**Comment by mhausenblas** [comment]
So, I'm still not following. The recipe 10.1 doesn't use a dedicated namespace (`sec` as you suggest here). The error message you see there means that you haven't created the namespace (you can do so by issuing the `kubectl create ns sec` command), but again, how is this relevant to the recipe, I wonder?

**Comment by bennybhlin** [comment]
Sorry I did not make it clear; what I mean is, yes the code snippet in printed book is correct - it does create a service account under default namespace; however, if I used another sample code from here (https://github.com/k8s-cookbook/recipes/blob/master/ch10/pod-with-sa.yaml), the service account would be created under name space 'sec':

![default](https://user-images.githubusercontent.com/38855622/47064221-1a296e80-d211-11e8-98d5-e2e4159df2b6.png)

Therefore, if readers copy and execute sample codes from URL above, other commands in this recipe would not work unless you add '-n sec' to them.

**Comment by mhausenblas** [comment]
Yes, I understand this @bennybhlin but I fail to see why this is an issue or how to address it since each of the recipes is (unless a dependency is called out explicitly) standalone. So, what do you suggest?

**Comment by bennybhlin** [comment]
OK, if all recipes are independent then I have no concern. (I thought it would be inherited by the next few recipes)

But for the code snippet above URL I would say removing 'namespace: sec' so it can be consistent with printed sample codes.

Or maybe we can simply remove sample code pod-with-sa.yaml of recipe 10.1? Because the demo service account can be created via kubectl command, so need to introduce this manifest file. (just an idea, it depends on you authors ^^)

**Comment by mhausenblas** [comment]
> OK, if all recipes are independent then I have no concern. (I thought it would be inherited by the next few recipes)

Yes, that's the general idea of O'Reilly cookbooks ;)


> But for the code snippet above URL I would say removing 'namespace: sec' so it can be consistent with printed sample codes.

> Or maybe we can simply remove sample code pod-with-sa.yaml of recipe 10.1? Because the demo service account can be created via kubectl command, so need to introduce this manifest file. (just an idea, it depends on you authors ^^)

Maybe I'm dense. I checked twice now but I can not find any mention of `pod-with-sa.yaml` in said recipe 10.1 …

**Comment by bennybhlin** [comment]
My fault. Certainly it's not mentioned in book. Because I saw it here (https://github.com/k8s-cookbook/recipes/tree/master/ch10), so I assumed that maybe readers would use it as well:

![default](https://user-images.githubusercontent.com/38855622/47072751-4a7d0700-d229-11e8-8502-4dfcf4fecf8b.png)

**Comment by mhausenblas** [comment]
Argh, now I see where the confusion comes from, thanks for pointing this out! Will fix it here, yes, thanks @bennybhlin
